name: Deploy Dist

on: 
  - push
  - workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Install Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Bulid Project
        run: npm run build

      - name: Deploy to server via SSH command
        run: echo "Deploying to server"